[project]
name = "paddle-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "paddleocr>=2.10.0",
    "paddlepaddle>=3.0.0",
    "setuptools>=80.4.0",
]
