#---------------------------------------
# Utility
#---------------------------------------
alias fresh='source $HOME/.bashrc'
alias path='echo -e ${PATH//:/\\n}'

#---------------------------------------
# python
#---------------------------------------
alias vactive='source venv/Scripts/activate'
alias pactive='source env/Scripts/activate'
alias pyclean='find . -type d -name "__pycache__" -exec rm -rf {} + \
    && find . -type f -name "*.pyc" -delete \
    && find . -type f -name "*.pyo" -delete \
    && rm -rf .pytest_cache/ *.egg-info/ build/ dist/'

#---------------------------------------
# ssh
#---------------------------------------
alias sshjskn='ssh kdy987@jskn.iptime.org -p 2020'

#---------------------------------------
# cd
#---------------------------------------
alias cdkavana='cd /c/Users/PC/Work/python25/rpa/kavana'